# Generated by Django 3.1.3 on 2020-12-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.FloatField()),
                ('cost', models.FloatField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'BUDGET',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField()),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'PAYMENT_DATA',
            },
        ),
        migrations.CreateModel(
            name='Paymentsplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_1', models.IntegerField()),
                ('percentage_2', models.IntegerField()),
                ('percentage_3', models.IntegerField()),
                ('percentage_4', models.IntegerField()),
            ],
            options={
                'db_table': 'PAYMENT_SPLIT',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField()),
                ('user_default', models.BooleanField()),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('paymentdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.paymentdata')),
                ('agency', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('enable', models.BooleanField()),
            ],
            options={
                'db_table': 'ACCOUNT',
            },
            bases=('core.paymentdata',),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('paymentdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.paymentdata')),
                ('flag', models.CharField(max_length=20)),
                ('enable', models.BooleanField()),
            ],
            options={
                'db_table': 'CREDIT_CARD',
            },
            bases=('core.paymentdata',),
        ),
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('parceled_out', models.BooleanField()),
                ('parceled_times', models.IntegerField()),
                ('parceled_freq', models.CharField(choices=[('day', 'daily'), ('week', 'weekly'), ('month', 'monthly'), ('semiannual', 'semiannual'), ('year', 'yearly')], default='month', max_length=10)),
                ('payment_meth', models.CharField(choices=[('cash', 'cash'), ('credit', 'credit card'), ('debit', 'debit'), ('etv', 'electronic transfer of values')], default='credit', max_length=6)),
                ('paid', models.BooleanField()),
                ('date_paid', models.DateTimeField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.category')),
                ('payment_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.paymentdata')),
                ('payment_split', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.paymentsplit')),
            ],
            options={
                'db_table': 'TRANSACT',
            },
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='personal_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='personal_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='personal_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='personal_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='budget',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
        migrations.AddField(
            model_name='budget',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user'),
        ),
    ]
