# Generated by Django 3.1.3 on 2020-12-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201202_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transact',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transact',
            name='parceled_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_default',
            field=models.BooleanField(default=False),
        ),
    ]
